/* Catalogul. Produse complet fictive, inventate pentru o demonstratie de design. */
var PRODUSE = [
  { id:'carina', nume:'Praf de Carina', constelatie:'Carina', semn:'Scorpion',
    culoare:'#b8ff45', tox:82, pret:249, stoc:12, forma:'Capsulă opacă',
    scurt:'Recoltat din marginea rece a nebuloasei. Se dizolvă în întuneric.',
    lung:'Se extrage din franjurii nebuloasei Carina, acolo unde gazul e destul de rece cât să se depună. Fiecare capsulă conține exact un grăunte. Culoarea vine din praful însuși, nu se adaugă nimic.',
    doza:'Un grăunte la 40 de zile standard', origine:'Brațul Sagittarius, 7.500 ani-lumină' },
  { id:'saturn', nume:'Umbra lui Saturn', constelatie:'Capricorn', semn:'Capricorn',
    culoare:'#8b6cff', tox:64, pret:198, stoc:7, forma:'Capsulă mată',
    scurt:'Condensat din partea inelului care nu vede niciodată soarele.',
    lung:'Partea interioară a inelului B rămâne în umbră aproape tot anul saturnian. Ce se depune acolo are o densitate pe care nu o găsești nicăieri altundeva în sistem. Recoltăm o dată la doi ani.',
    doza:'O capsulă la fiecare conjuncție', origine:'Inelul B, Saturn' },
  { id:'neutron', nume:'Sare de Neutron',  constelatie:'Lyra', semn:'Vărsător',
    culoare:'#5cf0d8', tox:97, pret:640, stoc:2, forma:'Cristal sigilat',
    scurt:'Cea mai grea marfă din catalog. Se livrează în cutie proprie.',
    lung:'Un bob cântărește cât o clădire. Cutia de transport face jumătate din preț și nu se poate returna. Nu deschideți în afara câmpului de sprijin.',
    doza:'Nu se administrează. Se ține.', origine:'Rămășiță de supernovă, Lyra' },
  { id:'cometa', nume:'Coadă de Cometă', constelatie:'Orion', semn:'Săgetător',
    culoare:'#ffd84d', tox:38, pret:129, stoc:24, forma:'Fiolă',
    scurt:'Prinsă din zbor. Are gust de gheață veche.',
    lung:'Cometele lasă în urmă un praf care se aprinde la contactul cu atmosfera. Îl prindem înainte, cu plase magnetice, pe traiectorie. Din zece treceri iese o fiolă.',
    doza:'Trei picături pe lună', origine:'Norul lui Oort' },
  { id:'vid', nume:'Vid Îmbuteliat', constelatie:'Vela', semn:'Balanță',
    culoare:'#9aa0cc', tox:12, pret:89, stoc:40, forma:'Sticlă goală',
    scurt:'Exact ce scrie pe etichetă. Nimic, foarte curat.',
    lung:'Golul dintre brațele galaxiei e cel mai curat vid la care avem acces. Sticlele se sigilează pe loc. Cine le deschide pe o planetă cu atmosferă pierde produsul în aceeași secundă.',
    doza:'Nu se consumă', origine:'Golul Local' },
  { id:'pulsar', nume:'Bătaie de Pulsar', constelatie:'Vulpecula', semn:'Berbec',
    culoare:'#ff5470', tox:88, pret:410, stoc:5, forma:'Capsulă ritmată',
    scurt:'Pulsează de 641 de ori pe secundă. Se aude prin cutie.',
    lung:'Fiecare capsulă păstrează ritmul stelei din care a fost extrasă. Nu se sincronizează cu nimic altceva și nu se oprește. Clienții spun că e cel mai greu de ținut în casă.',
    doza:'O bătaie pe zi', origine:'PSR B1937+21' },
  { id:'inel', nume:'Cenușă de Inel', constelatie:'Lyra', semn:'Pești',
    culoare:'#6cb6ff', tox:55, pret:175, stoc:16, forma:'Pulbere',
    scurt:'Ce rămâne dintr-o stea care s-a dezbrăcat încet.',
    lung:'Nebuloasa Inelul e o stea care și-a lepădat straturile pe rând, timp de zece mii de ani. Cenușa e ce a căzut ultima. Se macină singură.',
    doza:'Un vârf de cuțit, rar', origine:'Messier 57' },
  { id:'gaura', nume:'Margine de Orizont', constelatie:'Sagittarius', semn:'Scorpion',
    culoare:'#c77dff', tox:99, pret:1290, stoc:1, forma:'Nu se poate descrie',
    scurt:'Un singur exemplar. Nu se returnează, din motive fizice.',
    lung:'Materialul provine de la marginea orizontului de evenimente, de unde încă se mai poate ieși. Ce e dincolo nu ne interesează comercial. Livrarea durează cât durează.',
    doza:'Una singură, o dată', origine:'Sagittarius A*' }
];
