import { chromium } from 'playwright-core';
const baza='file:///Users/robert/ClaudeProjects/web-dev/web-demos/45-apoteca/';
const S='/private/tmp/claude-501/-Users-robert/adf39f36-5b09-4f36-a736-be1fc8abe29e/scratchpad/';
const b=await chromium.launch({channel:'chrome'});
const p=await b.newPage({viewport:{width:320,height:760}});
const e=[];p.on('pageerror',x=>e.push(String(x).split('\n')[0]));
await p.goto(baza+'index.html',{waitUntil:'load'});await p.waitForTimeout(1600);
await p.screenshot({path:S+'m-index.png'});
await p.click('.burger');await p.waitForTimeout(700);
await p.screenshot({path:S+'m-meniu.png'});
await p.click('.burger');await p.waitForTimeout(500);
await p.goto(baza+'produse.html',{waitUntil:'load'});await p.waitForTimeout(1600);
await p.evaluate(()=>document.getElementById('catalog').scrollIntoView({block:'start'}));
await p.waitForTimeout(900);
await p.screenshot({path:S+'m-catalog.png'});
const lat=await p.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);
console.log('depasire orizontala la 320:',lat);
console.log('erori JS:',e.length?e:'niciuna');
await b.close();
